
project_id = "ckfdybkkmmqqhersclrb"

[functions.send-reset-email]
verify_jwt = true

[functions.send-daily-reminders]
verify_jwt = true

[functions.send-ceo-daily-report]
verify_jwt = false

[functions.send-user-invitation]
verify_jwt = true

[functions.verify-invitation]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false
