// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckfdybkkmmqqhersclrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZmR5YmtrbW1xcWhlcnNjbHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjI4NzMsImV4cCI6MjA2NTI5ODg3M30.Zk2EcfscpYhMUOYXkWKTadn96c8EfJla73B1jhNSUz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);